EXP:
  EXP_ID: "vla0"
  MODEL: "qwen" 
  LR_SCHED: "none"
  AMP: True
  OPTIMIZER: "adamw"

TRAIN:
  lr: 5e-6
  num_epochs: 24
  clip_grad_norm: 0.0
  l2: 1e-10

EXP_EXTRA:
  save_ckp: 2

DATALOADER:
  batch_size: 8
  num_workers: 8
  ROBOVERSE:
    cfg_path: libs/RoboVerse/roboverse/configs/img_libero_aug.yaml
    cfg_opts: IMAGE.crop_img:0.875:IMAGE.img_size:224:IMAGE.cam_list:('3p1','3p2')

MODEL:
  QWEN:
    add_vision_id: True
    use_lora: False 
    use_qlora: False
    use_flash_attention_2: False
    rgb_img_size: 224,224
    original_action_dim: 7
    action_mask_aug_per: 0.4
    num_cam: 2
    tiled_rgb_imgs: True
